name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clear existing
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: cd /var/www/html && rm -rf plugin.video.fenda/* && rm -rf zips/* && python3 _repo_xml_generator.py && python3 update-build.py

      - name: Transfer files to fenda.live via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          settings: 'sftp:auto-confirm=yes'
          localDir: '.'
          remoteDir: ${{ secrets.SFTP_REMOTE_DIR }}
          reverse: true
          onlyNewer: true

      - name: Generate repo and update website build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          script: cd /var/www/html && rm -rf zips/* && python3 _repo_xml_generator.py && python3 update-build.py
